Repository rogervila/python_carbon, pull requests merged in 2022-03, with the labels that each got.

#9 [Bugfix] Fix Sonarcloud integration
  .github/workflows/pull_request.yml
Labels: bug

#8 Added more methods
  python_carbon/__init__.py
Labels: enhancement, good first issue

#12 [Feature] SonarCloud fetch depth
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
Labels: enhancement
